config/routes.rb
#encoding: UTF-8
Dir.glob("#{Rails.root.to_s}/config/routes/**/*.rb").each {|route_file| load(route_file)}
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base] # 解决Forbidden

Rails.application.routes.draw do
  Routes::OpenRoutes.draw(self)
  Routes::BoomboxRoutes.draw(self)
  Routes::BoomboxOperationRoutes.draw(self)
  Routes::BoomboxDjRoutes.draw(self)

  root to: 'boombox/dj/home#index' #首页自动跳转至DJ后台

  # # app帮助
  # get "/helps" => 'pages#show_help'
  # get "/helps/:position" => 'pages#show_sub_help'
  #
  # # web
  # get "/about" => 'pages#about'

  # # wap
  # get "/mobile" => 'pages#wap_index'
  # get "/mobile_about" => 'pages#wap_about'
  # get "/service/terms" => 'pages#wap_terms'
  #
  # #app下载
  # get "/mobile/download" => 'pages#download'
  # get '/app/download', to: 'pages#app_download'
  #
  # #分享页
  # get "/mobile/shows/sharing" => "pages#sharing_show"
  # get "/mobile/concerts/sharing" => "pages#sharing_concert"
  #
  # #版权页
  # get "/copyright" => "pages#boombox_copyright"

  namespace :api do
    namespace :v1 do
      post "alipay/notify" => "alipay#notify"

      post "alipay/refund_notify" => "alipay#refund_notify"

      get "express_detail" => "express_detail#index"

      post 'feedbacks' => "feedbacks#create"

      resources :admins do
        collection do
          post "sign_in"
        end
      end

      resources :users do
        collection do
          post "verification"
          post "sign_in"
          post "get_user" => "users#get_user"
          post "update_user" => "users#update_user"
          post "follow_subject" => "users#follow_subject"
          post "unfollow_subject" => "users#unfollow_subject"
          post "vote_concert" => "users#vote_concert"
          post "followed_stars" => "users#followed_stars"
          post "followed_shows" => "users#followed_shows"
          post "followed_concerts" => "users#followed_concerts"
          post "create_topic" => "users#create_topic"
          post "like_topic" => "users#like_topic"
          post "create_comment" => "users#create_comment"
          post "create_order" => "users#create_order"
          post "update_express_info" => "users#update_express_info"
        end
      end

      resources :banners
      resources :startup

      resources :stars do
        collection do
          get "search"
        end
      end
      resources :concerts do
        member do
          get "city_rank"
        end
      end
      resources :shows do
        member do
          get "preorder"
          get "seats_info"
          get "click_seat"
        end
      end
      resources :topics
      resources :comments
      resources :cities
      resources :stadiums
      resources :messages
      resources :tickets do
        collection do
          post :check_tickets
          get :get_ticket
        end
      end
      resources :areas
      resources :orders, only: [:index, :show] do
        collection do
          get :orders_for_soon
        end
        member do
          post :pay
          get :show_for_qr_scan
        end
      end
    end
  end

  namespace :operation do
    root to: "home#index"
    match "/home/get_graphic_data" => "home#get_graphic_data", via: [:get]
    mount Sidekiq::Web => '/sidekiq'
    resources :sessions, only: [:new, :create, :destroy]
    match "/signin" => "sessions#new", via: [:get]
    match "/signout" => "sessions#destroy", via: [:delete]

    resources :helps do
      collection do
        post :sort
      end
    end

    resources :banners do
      collection do
        post :sort
      end
    end
    resources :videos do
      member do
        patch :set_main
      end
    end
    resources :stars do
      collection do
        post :sort
      end
      member do
        get :get_topics
        post :new_show
      end
    end
    resources :concerts do
      member do
        get :get_city_topics
        get :get_city_voted_data
        get :get_cities
        post :add_concert_city
        post :update_base_number
        post :add_star
        delete :remove_star
        get :refresh_map_data
        delete :remove_concert_city
        patch :toggle_is_top
        post :send_create_message
      end
      collection do
        get :search
      end
    end
    resources :shows do
      collection do
        get "get_city_stadiums"
        post :upload
      end
      member do
        post "update_area_data"
        patch :toggle_is_top
        post :new_area
        delete :del_area
        get :seats_info
        post :update_seats_info
        post :add_star
        delete :del_star
        post :set_area_channels
        get :event_list
        get :event_detail
        post :add_event
        patch :update_event
        delete :del_event
        post :upload_map
        get :get_coordinates
        patch :toggle_area_is_top
        post :update_event_info
        post :toggle_event_is_display
      end
    end
    resources :orders do
      member do
        post :set_order_to_success
        post "update_express_id"
        get :manual_send_msg
        post "update_order_data"
        post :update_buy_price
        post :finish_order
      end
      collection do
        get :search
        get :search_express
      end
    end
    resources :users, only: [:index, :show] do
      member do
        post :block_user
        post :remove_avatar
      end
      collection do
        get :search
      end
    end
    resources :admins, except: [:destroy] do
      member do
        post :block_admin
      end
    end
    resources :topics, only: [:create, :edit, :update, :index] do
      member do
        get :refresh_comments
        post :add_comment
        delete :destroy_comment
        delete :destroy_topic
        post :set_topic_top
        post :update_topic_is_top
      end
    end
    resources :tickets do
      collection do
        get :search
      end
    end
    resources :messages do
      member do
        post :send_umeng_message_again
      end
    end
    resources :comments
    resources :cities, except: [:show, :destroy] do
      collection do
        get :search
      end
    end
    resources :stadiums, except: [:show, :destroy] do
      collection do
        get :search
      end
      member do
        get :refresh_areas
        post :submit_area
        delete :del_area
      end
    end
    resources :startup, except: [:new, :show, :edit] do
      member do
        post :set_startup_status
      end
    end
    resources :feedbacks, only: [:index, :destroy]
    resources :site_setting do
      post :set_block, on: :member
    end
    resources :static_pages, except: [:show, :destroy] do
      get :description, on: :member
    end
    #TODO api_auth
  end

  get "description", to: "description#show"
  get "express_detail", to: "express_detail#show"
  get "seats_map", to: "seats_map#show"

  #simditor_image
  post '/simditor_image', to: 'simditor_image#upload'

  #永乐退款回调
  post '/lmapplyRefund', to: 'yongle#refund'
end

app/models/operation.rb
#encoding: UTF-8
module Operation
  def self.table_name_prefix
    'operation_'
  end
end

app/controllers/api/v1/shows_controller.rb
# encoding: utf-8
class Api::V1::ShowsController < Api::V1::ApplicationController
  before_action :check_has_user
  before_action :get_show, except: [:index]
  skip_before_filter :api_verify, only: [:click_seat]

  def index
    @shows = Show.is_display.page(params[:page])
  end

  def show
  end

  def preorder
    @stadium = @show.stadium
  end

  def seats_info
    @area = @show.areas.find_by_id(params[:area_id])
  end

  def click_seat
    render nothing: true
  end

  private
  def get_show
    @show = Show.find(params[:id])
  end
end

app/controllers/boombox/operation/activities_controller.rb
# encoding: utf-8
class Boombox::Operation::ActivitiesController < Boombox::Operation::ApplicationController
  before_filter :get_activity, except: [:search, :index, :new, :create, :upload_image]

  def index
    params[:activities_page] ||= 1
    params[:activities_per] ||= 10
    activities = BoomActivity.activity

    if params[:activities_start_time].present?
      activities = activities.where("created_at > '#{params[:activities_start_time]}'")
    end

    if params[:activities_end_time].present?
      activities = activities.where("created_at < '#{params[:activities_end_time]}'")
    end

    if params[:activities_is_hot].present?
      activities = activities.where(is_hot: params[:activities_is_hot])
    end

    if params[:activities_q].present?
      activities = activities.where("name like ?", "%#{params[:activities_q]}%")
    end

    @activities = activities.page(params[:activities_page]).order("created_at desc").per(params[:activities_per])

    respond_to do |format|
      format.html
      format.js
    end

  end

  def new
    @activity = BoomActivity.new
    @tags = get_all_tag_names
    @activity_collaborators = Collaborator.verified.pluck(:nickname)
  end

  def create
    @activity = BoomActivity.new(activity_params)
    @activity.mode = "activity"

    if @activity.save
      if params[:boom_activity][:activity_tag_names].present?
        subject_relate_tag(params[:boom_activity][:activity_tag_names], @activity)
      end

      if params[:boom_activity][:activity_collaborator_nicknames].present?
        collaborator_nicknames_array = params[:boom_activity][:activity_collaborator_nicknames].split(",")
        collaborators = Collaborator.where(nickname: collaborator_nicknames_array)
        collaborator_ids = collaborators.pluck(:id)
        collaborators.each do |c|
          c.collaborator_activity_relations.where(boom_activity_id: @activity.id).first_or_create!
        end
        @activity.collaborator_activity_relations.where.not(collaborator_id: collaborator_ids).delete_all
      end

      flash[:notice] = '创建活动成功'
    else
      flash[:alert] = '创建活动失败'
    end

    redirect_to boombox_operation_activities_url
  end

  def update
    if @activity.update(activity_params)
      if params[:boom_activity][:activity_tag_names].present?
        subject_relate_tag(params[:boom_activity][:activity_tag_names], @activity)
      end

      if params[:boom_activity][:activity_collaborator_nicknames].present?
        collaborator_nicknames_array = params[:boom_activity][:activity_collaborator_nicknames].split(",")
        collaborators = Collaborator.where(nickname: collaborator_nicknames_array)
        collaborator_ids = collaborators.pluck(:id)
        collaborators.each do |c|
          c.collaborator_activity_relations.where(boom_activity_id: @activity.id).first_or_create!
        end
        @activity.collaborator_activity_relations.where.not(collaborator_id: collaborator_ids).delete_all
      end
      flash[:notice] = '编辑活动成功'
    else
      flash[:alert] = '编辑活动失败'
    end

    redirect_to boombox_operation_activities_url
  end

  def edit
    @tags = get_all_tag_names
    @activity_collaborators = Collaborator.verified.pluck(:nickname)
  end

  def change_is_top
    #只有一个置顶，update all(is_top)
    if @activity.is_top
      @activity.update(is_top: false)
    else
      BoomActivity.activity.update_all(is_top: false)
      @activity.update(is_top: true)
    end
    redirect_to boombox_operation_activities_url
  end

  def change_is_hot
    if @activity.is_hot
      @activity.update(is_hot: false)
    else
      @activity.update(is_hot: true)
    end
    redirect_to boombox_operation_activities_url
  end

  def upload_cover
    @activity.update(activity_params)

    render json: {success: true, cover_path: @activity.cover_url}
  end

  def upload_image
    image = SimditorImage.create(image: params[:file])
    render json: {file_path: image.image_url}
  end

  private
  def get_activity
    @activity = BoomActivity.find(params[:id])
  end

  def activity_params
    params.require(:boom_activity).permit(:cover, :name, :is_hot, :is_display, :description)
  end
end

app/controllers/boombox/operation/application_controller.rb
# encoding: utf-8
class Boombox::Operation::ApplicationController < ApplicationController
  layout "boombox_operation"

  before_filter :check_login!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to boombox_operation_root_url, :alert => exception.message
  end

  def subject_relate_tag(tag_names = [], subject = nil, need_del_tag = true)
    if subject && tag_names.present?
      tags_array = []
      tag_names.split(",").each do |name|
        downcase_name = name.gsub(/\s/, "").downcase
        tag = BoomTag.where(lower_string: downcase_name).first_or_create(name: name)
        tags_array.push(tag) if tag
      end
      tags_array.each do |tag|
        tag.tag_subject_relations.where(subject_id: subject.id, subject_type: subject.class.name).first_or_create!
      end
      #对艺术家来说，只需要创建，关联标签，不需要删除标签

      subject.tag_subject_relations.where.not(boom_tag_id: tags_array.map{|tag| tag.id}).delete_all if need_del_tag
    end
  end

  def get_subject_tags(subject = nil)
    subject.present? ? subject.boom_tags.pluck(:id) : []
  end

  def get_all_tag_names
    BoomTag.valid_tags.pluck(:name)
  end

  protected

  def check_login!
    unless current_admin
      session[:request_page] = request.original_url
      flash[:notice] = "Please login"
      redirect_to boombox_operation_signin_url
    end
  end

  def current_admin
    @current_admin ||= BoomAdmin.find_by_id(session[:admin_id]) if session[:admin_id]
  end

  def current_ability
    @current_ability ||= ::Ability.new(current_admin)
  end

  def unverified_count
    @unverified_count ||= Collaborator.where(verified: 0).count
  end

  def unread_count
    @unread_count ||= BoomFeedback.where(status: 0).count
  end

  helper_method :current_admin, :unverified_count, :unread_count
end

app/controllers/boombox/operation/boom_admins_controller.rb
# encoding: utf-8
class Boombox::Operation::BoomAdminsController < Boombox::Operation::ApplicationController
  before_filter :get_boom_admin, except: [:index, :new, :create]

  def index
    @boom_admins = BoomAdmin.where.not(admin_type: 2).page(params[:page]).order("created_at desc")
  end

  def new
    @boom_admin = BoomAdmin.new
  end

  def create
    @boom_admin = BoomAdmin.new(name: params[:boom_admin_new_username], admin_type: params[:admin_type].to_i)
    @boom_admin.set_password(params[:boom_admin_new_password])

    if @boom_admin.save
      flash[:notice] = '管理员创建成功'
      redirect_to boombox_operation_boom_admins_url
    else
      flash[:alert] = @boom_admin.errors.full_messages
      render :new
    end
  end

  def update
    if params[:boom_admin_edit_pw1].present? && params[:boom_admin_edit_pw1] == params[:boom_admin_edit_pw2]
      @boom_admin.set_password(params[:boom_admin_edit_pw1])
    end
    if @boom_admin.save
      flash[:notice] = '修改成功'
      redirect_to boombox_operation_boom_admins_url
    else
      flash[:alert] = @boom_admin.errors.full_messages
      render :update
    end
  end

  def edit
  end

  def block_admin
    @boom_admin.update(is_block: params[:block])

    redirect_to boombox_operation_boom_admins_url
  end

  private
  def get_boom_admin
    @boom_admin = BoomAdmin.find(params[:id])
  end
end

app/controllers/boombox/operation/boom_albums_controller.rb
class Boombox::Operation::BoomAlbumsController < Boombox::Operation::ApplicationController
  load_and_authorize_resource

  def index
    # 先有艺人再上传
    unless params[:collaborator_id].present?
      redirect_to boombox_operation_collaborators_url
    end

    # 显示
    params[:page] ||= 1
    @boom_albums = BoomAlbum.where(collaborator_id: params[:collaborator_id]).order(is_cover: :desc, created_at: :desc).page(params[:page])
    # 上传
    @collaborator = Collaborator.find(params[:collaborator_id])
    @boom_album = BoomAlbum.new
  end

  def create
    @collaborator = Collaborator.find(params[:boom_album][:collaborator_id])
    @boom_album = @collaborator.boom_albums.new(boom_album_params)
    if @boom_album.save
      # set cover
      @boom_albums = BoomAlbum.where(collaborator_id: @collaborator.id)
      @boom_albums.update_all(is_cover: false)
      @boom_album.update(is_cover: true)

      respond_to do |format|
        flash[:notice] = '上传成功'
        format.json {render nothing: true}
      end
    else
      flash[:alert] = @boom_album.errors.full_messages
      redirect_to boombox_operation_boom_albums_url(collaborator_id: @collaborator.id)
    end
  end

  def set_cover
    @boom_album.update(is_cover: true)
    flash[:notice] = "设置封面成功"
    redirect_to boombox_operation_boom_albums_url(collaborator_id: @boom_album.collaborator.id)
  end

  def unset_cover
    @boom_album.update(is_cover: false)
    flash[:notice] = "取消封面成功"
    @collaborator = Collaborator.find(params[:collaborator_id])
    warn_if_current_no_cover(@collaborator)

    redirect_to boombox_operation_boom_albums_url(collaborator_id: @boom_album.collaborator.id)
  end

  def destroy
    @boom_album.destroy
    flash[:notice] = "相片删除成功"
    @collaborator = Collaborator.find(params[:collaborator_id])
    warn_if_current_no_cover(@collaborator)

    redirect_to boombox_operation_boom_albums_url(collaborator_id: @boom_album.collaborator.id)
  end

  private

  def boom_album_params
    params[:boom_album][:image] = params[:file]
    params.require(:boom_album).permit(:collaborator_id, :image, :is_cover)
  end

  def warn_if_current_no_cover(collaborator)
    unless collaborator.boom_albums.where(is_cover: true).any?
      flash[:warning] = "艺人当前没有封面，请设置或上传"
    end
  end
end

app/controllers/boombox/operation/boom_comments_controller.rb
class Boombox::Operation::BoomCommentsController < Boombox::Operation::ApplicationController
  load_and_authorize_resource

  def hide
    @boom_comment.update_attributes(is_hidden: true)
    flash[:notice] = "屏蔽成功"
    redirect_to boombox_operation_boom_topic_url(@boom_comment.boom_topic)
  end
end

app/views/operation/shows/_area_table.html.erb
<%# encoding: utf-8 %>

<% event.areas.order("is_exist DESC").each do |area| %>
  <% sold_tickets_count = show.sold_tickets_count(area.id) %>
  <% relation = ShowAreaRelation.where(show_id: show.id, area_id: area.id).first %>
  <tr area_id="<%= area.id %>" color="<%= area.color %>" area_name="<%= area.name %>">
    <% if show.selected? && relation %>
      <td class="area_name_<%= area.id %>"><%= text_field_tag "area_name", area.name, class: 'form-control', disabled: true %></td>
      <td class="price_<%= area.id %>"><%= text_field_tag "area_price", relation.try(:price), class: 'form-control', disabled: true %></td>
      <% if @show.viagogo? %>
        <% price_range = relation.price_range %>
        <td ><%= price_range.present? ? price_range : "没有数据" %></td>
        <td><%= area.is_exist ? "在售" : "已售罄" %></td>
      <% end %>
      <td class="seats_count_<%= area.id %>"><%= text_field_tag "area_seats_count", relation.try(:seats_count), class: 'form-control', disabled: true %></td>
      <td class="left_seats_<%= area.id %>"><%= relation.try(:left_seats) %></td>
      <td class="sold_tickets_<%= area.id %>"><%= sold_tickets_count %></td>
      <td data-id="<%= area.id %>" data-channels="<%= relation.channels %>">
        <%= button_tag "修改", class: "btn btn-default editable_toggle" %>
        <%= link_to "保存", 'javascript:void(0);', class: 'change_show_area_data btn btn-default' %>
        <%= link_to "删除", 'javascript:void(0);', class: 'del_area btn btn-danger' %>
        <%= link_to (area.is_top ? "取消置顶" : "置顶"), 'javascript:void(0);', class: 'btn btn-default set_top' %>
        <%= link_to '设置渠道', 'javascript:void(0);', class: 'set_channel btn btn-info' if can? :set_channels, current_admin %>
      </td>
    <% elsif show.selectable? %>
      <td><%= area.name %></td>
      <td><%= relation.try(:seats_count) %></td>
      <td><%= relation.try(:left_seats) %></td>
      <td class="sold_tickets_<%= area.id %>"><%= sold_tickets_count %></td>
      <td data-id="<%= area.id %>">
        <%= link_to "设置选座", seats_info_operation_show_path(show, area_id: area.id), class: 'btn btn-default' %>
        <%= link_to (area.is_top ? "取消置顶" : "置顶"), 'javascript:void(0);', class: 'btn btn-default set_top' %>
        <%= link_to "删除", 'javascript:void(0);', class: 'del_area btn btn-danger' %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/operation/shows/_table.html.erb
<%# encoding: utf-8 %>

<table id="shows_table" class="table table-hover shows" data-source="<%= operation_shows_url(format: 'json') %>">
  <thead>
    <tr>
      <th class='text-center'>演出名称</th>
      <th class='text-center'>演出艺人</th>
      <th class='text-center'>是否显示</th>
      <th class='text-center'>是否预售</th>
      <th class='text-center'>资源提供方</th>
      <th class='text-center'>选座类型</th>
      <th class='text-center'>购票状态</th>
      <th class='text-center'>票的类型</th>
      <th class='text-center'>演出地点</th>
      <th class='text-center'>演出时间</th>
      <th class='text-center'>售出票数／总票数</th>
      <th class='text-center'>操作</th>
    </tr>
  </thead>
  <tbody class='text-center'>
  </tbody>
</table>

<%= content_tag :div, id: 'shows_filter', data: {
  show_type_filter: @show_type_filter,
  status_filter: @status_filter,
  source_filter: @source_filter,
  is_display_filter: @is_display_filter
} do %>
<% end %>

app/views/operation/shows/event_list.html.erb
<div class="nav">
  <h1><%= @show.name %> - 场次管理</h1>
  <%= link_to '增加场次', '##', class: 'btn btn-default', data: {toggle: 'modal', target: '.addEventModal'} %>
</div>
<div class="event_list">
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>是否显示</th>
        <th>描述时间</th>
        <th>开始时间</th>
        <th>结束时间</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.id %></td>
          <td><%= event.is_display ? "显示" : "隐藏" %></td>
          <td><%= event.description_time %></td>
          <td><%= get_datetime event.show_time %></td>
          <td><%= get_datetime event.end_time %></td>
          <td>
            <%= link_to '详情', event_detail_operation_show_url(@show, event_id: event.id) %>
            <%= link_to (event.is_display ? '隐藏' : '显示'), toggle_event_is_display_operation_show_url(@show, event_id: event.id), method: "post" %>
            <%= link_to '删除', del_event_operation_show_url(@show, event_id: event.id), method: "delete", data: {confirm: "已售出的场次请勿删除，否则会影响验票入场，确定要删除吗？"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- 增加场次 -->
<div class="modal fade addEventModal" tabindex="-1" role="dialog" aria-labelledby="addEventModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%= simple_form_for @events.new, url: add_event_operation_show_path(@show) do |f| %>
          <%= f.input :is_multi_day, label: '是否多日套票' %>
          <%= f.input :is_display, label: '是否显示' %>
          <%= f.input :show_time, as: :string, label: '开始时间' %>
          <%= f.input :end_time, as: :string, label: '结束时间' %>
          <%= submit_tag '提交', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= hidden_field_tag 'show_id', @show.id %>

app/views/operation/shows/index.html.erb
<%# encoding: utf-8 %>

<div class="nav show-index">
  <h1 class="pull-left">演出列表</h1>
  <%= link_to '发布新演出', new_operation_show_path, class: 'btn btn-primary add-show' %>
</div>

<div class="shows_list mt20">
  <%= render partial: "table", locals: {shows: @shows} %>
</div>

app/views/operation/shows/show.html.erb
<%# encoding: utf-8 %>

<div class="nav show_show">
  <h2><%= @show.name %></h2>
  <% if can? :update, @show %>
    <%= link_to "编辑", edit_operation_show_path(@show) %>
  <% end %>
  <%= link_to "场次管理", event_list_operation_show_path(@show) %>
  <div class="row">
    <div class="col-lg-6">
      <dl class="dl-horizontal">
        <dt class="dt-left">购票状态</dt><dd><%= @show.status_cn %></dd>
        <dt class="dt-left">是否预售</dt><dd><%= @show.is_presell_cn %></dd>
        <dt class="dt-left">是否显示</dt><dd><%= @show.is_display_cn %></dd>
        <dt class="dt-left">演出类型</dt><dd><%= @show.play_type %></dd>
        <dt class="dt-left">演出时间</dt><dd><%= get_datetime @show.show_time %></dd>
        <dt class="dt-left">演出城市</dt><dd><%= @show.city.name %></dd>
        <dt class="dt-left">演出场馆</dt><dd><%= @show.stadium.name %></dd>
      </dl>
    </div>
    <div class="col-lg-6">
      <p>演出海报</p>
      <img src="<%= @show.poster_url %>" alt="演出海报" width="300px">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <p>图文详情</p>
      <div><%= @show.description.html_safe %></div>
    </div>
  </div>
</div>